# Generated by Django 4.2.20 on 2025-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todo", "0003_todo_updated_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="updated_at",),
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.CharField(default="no", max_length=200),
        ),
    ]
